# The URL the site will be built for
base_url = "https://iroh.computer"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[[extra.docs_sidebar]]
section = "iroh"
links = [
 { title = "Overview", path = "/docs" },
 { title = "Install", path = "/docs/install" },
 { title = "Quickstart", path = "/docs/quickstart" },
 { title = "Services", path = "/docs/services" },
 { title = "Metrics", path = "/docs/metrics" },
 { title = "Concepts", path = "/docs/concepts" },
 { title = "Iroh & Kubo (go-IPFS)", path = "/docs/iroh-and-kubo" },
 { title = "Use Cases", path = "/docs/use-cases" },
]

[[extra.docs_sidebar]]
section = "platforms"
links = [
  { title = "Overview", path = "/docs/platforms" },
  { title = "cloud", path = "/docs/platforms/cloud" },
  { title = "mobile", path = "/docs/platforms/mobile" },
]

[[extra.docs_sidebar]]
section = "reference"
links = [
  { title = "Data Locations", path = "/docs/data-locations" },
  { title = "CLI", path = "/docs/cli" },
  { title = "configuration", path = "/docs/config" },
  { title = "configuration: store", path = "/docs/cloud/quickstart-gateway" },
  { title = "configuration: p2p", path = "/docs/cloud/quickstart-gateway" },
  { title = "configuration: gateway", path = "/docs/cloud/quickstart-gateway" },
]

# [[extra.docs_sidebar]]
# section = "iroh one"
# links = [
#   { title = "Overview", path = "/docs/one" },
# ]